import "@/styles/globals.css";

import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Geist } from "next/font/google";
import { auth } from "@/server/auth";
import { Toast } from "@/lib/toast";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	// Obtém a sessão do lado do servidor
	const session = await auth();
	console.log("Session:", session);


	return (
		<SessionProvider session={session}>
			<Toast>
				<html lang="pt" className={`${geist.variable}`}>
					<body>{children}</body>
				</html>
			</Toast>
		</SessionProvider>
	);
}